nette/application

src/Application/Routers/Route.php

This makes it about 40 % faster with the following benchmark. However it relies on `$refUrl` being immutable.
```php
$appRequest = new AppRequest('Admin', 'GET', ['action' => 'default']);
$refUrl = new UrlScript('http://localhost/');
$time = -microtime(true);
$routerB = new RouteList();
$routerB[] = new Route('', 'Homepage:default');
$routerB[] = new Route('sign-in', 'Auth:signIn');
$routerB[] = new Route('sign-out', 'Auth:signOut');
$routerB[] = new Route('sign-up', 'Auth:signUp');
$routerB[] = new Route('sign-up-confirm', 'Auth:signUpConfirm');
$routerB[] = new Route('forgotten-pass', 'Auth:forgottenPassword');
$routerB[] = new Route('view', 'Product:view');
$routerB[] = new Route('manage', 'Product:manage');
$routerB[] = new Route('dashboard', 'Dashboard:default');
$routerB[] = new …
```

Router: optimized for a single immutable $refUrl instance

---

src/Bridges/ApplicationDI/RoutingExtension.php

It's better for the future to not rely on the application alias. Also it's better to use `ContainerBuilder::getByType()` to find the service because the name of ApplicationExtension can vary as well. Of course `ContainerBuilder::getByType()` doesn't work in loadConfiguration, hence I moved the code to beforeCompile.

Fixed routing debugger

---

src/Application/PresenterFactory.php
src/Application/UI/Presenter.php
src/Bridges/ApplicationDI/ApplicationExtension.php
src/Bridges/ApplicationDI/PresenterFactoryCallback.php
tests/Application.DI/ApplicationExtension.invalidLink.phpt
tests/Application.Routers/LinkGenerator.phpt
tests/Application/Presenter.link().phpt
tests/Application/PresenterFactory.formatPresenterClass.phpt
tests/Application/PresenterFactory.unformatPresenterClass.phpt

Two different things.
1) replaced PresenterFactory dependency on DI with simple callback. 
- dependency on DIC is bad (it is the only one dependency on DIC in whole framework)
- current PresenterFactory constructor is different in 2.2 and 2.3, so there will still be BC break
- partially solves #16 
2) new invalidLinkMode
- handling of invalid links is not insufficient, we need warnings
- I am not happy with #65, where (for partial combatibility) is mode that triggers warnings named `INVALID_LINK_SILENT`

PresenterFactory as callback & changed invalid link handling [WIP]

---

src/Application/Responses/FileResponse.php
tests/Application/FileResponse.contentDisposition.phpt

According to RFC 5987 Content-Disposition filename should not contain non-US-ASCII characters.
Proper way to encode filename is this:
"filename*=utf-8''%C5%BElu%C5%A5ou%C4%8Dk%C3%BD%20k%C5%AF%C5%88.txt".
Unfortunately, RFC 5987 is not supported by all browsers, so for compatibility reasons, filename should be sent like this:
"filename=žluťoučký kůň.txt; filename*=utf-8''%C5%BElu%C5%A5ou%C4%8Dk%C3%BD%20k%C5%AF%C5%88.txt".
Some discussion about this is here: http://stackoverflow.com/questions/93551/how-to-encode-the-filename-parameter-of-content-disposition-header-in-http

Proper enconding of Content-Dispisition filename

---

src/Bridges/ApplicationLatte/ILatteFactory.php

After removing use definition from Nette\Bridges\ApplicationLatte\ILatteFactory was created a undefined namespace for Latte\Engine.
Resolve #84

Add missing use definition in ILatteFactory

---

src/Bridges/ApplicationLatte/TemplateFactory.php

Ref: https://forum.nette.org/en/24756-unclear-error-message-when-translator-is-not-set-to-template

Template: better error message when Translator is not set

---

src/Application/Responses/JsonResponse.php

The json output isn't something special what shouldn't be cached at all. If disabling of cache is needed, this should be handled by Nette Presenter itself.
It's probably BC Break.

json response: removed automatic cache disabling

---

src/Bridges/ApplicationLatte/UIMacros.php
tests/Bridges.Latte/UIMacros.renderSnippets4.phpt
tests/Bridges.Latte/expected/UIMacros.dynamicsnippets.alt.phtml
tests/Bridges.Latte/expected/UIMacros.dynamicsnippets.phtml
tests/Bridges.Latte/expected/UIMacros.snippet.alt.phtml
tests/Bridges.Latte/templates/snippets.includeblock.latte
tests/Bridges.Latte/templates/snippets.includeblock.sub2.latte

Snippets: do not render snippets from template which is included using includeblock macro

---

src/Application/UI/Form.php
src/Application/UI/Presenter.php
tests/UI/Presenter.parameters.phpt

nette/forms#33 nette/nette#1061

Attempt to solve mixing GET & POST params in AJAX without BC break

---

composer.json
src/Application/UI/Presenter.php
tests/UI/Presenter.storeRequest().phpt

As far as I can tell nette/security seems to be optional everywhere in nette/application.

Remove dependency on nette/security

---

src/Bridges/ApplicationLatte/VariableTemplate.php

Quite a few custom macros use something like: https://github.com/brabijan/images/blob/master/src/Brabijan/Images/Macros/Latte.php#L138

VaribaleTemplate: add getParameters() method to improve back compatability

---

src/Application/UI/Control.php
tests/Bridges.Latte/UIMacros.renderSnippets.phpt
tests/Bridges.Latte/expected/UIMacros.renderSnippets.html
tests/Bridges.Latte/templates/snippet-include.latte

Nested snippets were rendered multiple times when you used `->redrawControl()` without snippet name.
ref https://github.com/ublaboo/datagrid/issues/241
It should not be a BC break

Control - snippets: prevents multiple rendering of nested snippets

---

src/Bridges/ApplicationLatte/SnippetBridge.php

Root control is always IRenderable since it can only be Control (which implements IRenderable).
cc @matej21

SnippetBridge: Remove IRenderable check (Control is always IRenderable)

---

src/Application/LinkGenerator.php
tests/Routers/LinkGenerator.phpt

This fixes inconsistent between `$presenter->link` and `$linkGenerator->link`. Presenter throws exception, but LinkGenerator returns URL, for example `http://www.example.com/presenter/action?0=10`.

LinkGenerator: throws exception, when try to pass non-associative parameters to missing action

---

src/Application/UI/ComponentReflection.php
tests/UI/ComponentReflection.parseAnnotation.phpt

Fixed unescaped annotation name $name in preg_match_all function $pattern parameter. (Causing errors if annotation is like @Secured\User - ipub/permissions package)

FIX: Unescaped preg_match_all parameter

---

src/Application/UI/Presenter.php
tests/Application/Presenter.twoDomains.phpt

- bugfix
- documentation - not needed
- BC break - no
The pull request fixes issue when testing presenters without isolation: You make two presenter calls with Nette\Http\Request-s on different domains - the first domain is cached for whole class (and not only instance) and so the second instance of the same presenter will redirect you to the first domain.
The test is appended mainly as example (there's no problem to remove it if it's not needed).

Presenter: removed static from refUrl variable

---

src/Application/UI/ComponentReflection.php
tests/UI/ComponentReflection.parseAnnotation.phpt

I know it's internal class, but I am using it anyway - so it's maybe my problem. And I know about this issue quite long, but [with this commit](https://github.com/nette/application/commit/03b8b34a0518b7adc09883564dccaacde738af22) I have to fix it. In current master you can have `@privatex` annotation and this test will pass:
```php
Assert::same([TRUE], Reflection::parseAnnotation($rc, 'private'));
```
But I don't think this is right. Previously I was calling it like this:
```php
$visible = ComponentReflection::parseAnnotation($actionReflection, 'public\\s');
```
But it's not possible now... :)

ComponentReflection::parseAnnotation: fix false positive annotation parsing

---

src/Application/Routers/Route.php

It happened in some of my failing tests because `$refUrl->getScheme()` was empty for whatever reason.
Anyway a PHP warning should be fixed.

Fix possible PHP warning "strpos(): Offset not contained in string"

---

tests/Routers/Route.filter.url.object.phpt

Fix IDE static error. It show static error about using private property on `((object)$property)->id`

Rename Object to RouterObject

---

src/Application/Routers/Route.php
tests/Routers/Route.filter.global.phpt

I was doing some changes in structure of my application and I have found something what is IMHO bug.
In short: right now, the global input filter gets module and presenter split (like this: [Module: 'Front', Presenter: 'Homepage']) but output filter gets them together as presenter ([Presenter: 'Front:Homepage']).
Wouldn't it be better to unify the behaviour of those two functions to get the params split in both cases?

Route::constructUrl(): split of module and presenter moved before global filter

---

src/Application/UI/Presenter.php

- bug fix? yes
Code has to be number. With NULL error was thrown with message `Wrong parameters for Nette\Application\UI\InvalidLinkException([string $message [, long $code [, Throwable $previous = NULL]]])`.

Presenter: fixed type of $code  in throwing InvalidLinkException

---

src/Bridges/ApplicationDI/RoutingExtension.php
tests/Bridges.DI/RoutingExtension.basic.phpt

An alternative way to add new Route to RouteList. It moves control over the Route class into the RouteList, so Neon configuration for RoutingExtension can be used by other combination of classes descended from Nette*\RouteList and Nette*\Route.

RoutingExtension: added support for custom single-route classes.

---

src/Application/UI/Control.php

I'm removing typehint for display Nette\Utils\Html in $message
- bug fix? no
- new feature? no
- BC break? no

Remove typehint for $message in flashMessage

---

src/Application/Responses/FileResponse.php
tests/Responses/FileResponse.full.phpt

Since `4e6` is float and function `fread()` exects integer value for
length, it caused a `TypeError` on bigger files.
- bug fix? yes
- BC break? no

FileResponse: strict type fix

---

src/Application/Routers/Route.php

- bug fix? no  
- new feature? no
- BC break? no
- doc PR: nette/docs
THis just makes inflectors methods inside routes public. I bumped already in two project that I needed this code when developing some custom routes, and I think others also. In any way can't find anything harmful in this. Was also thinking to extract those methods maybe to RoutingHelper or something like that...

change Route inflectors visibility to public

---

src/Application/UI/Presenter.php

In the master branch response defaults to VoidResponse so it is never null in onShutdown event.

Fix docblock

---

composer.json
src/Application/Application.php
src/Application/IRouter.php
src/Application/LinkGenerator.php
src/Application/MicroPresenter.php
src/Application/Routers/Route.php
src/Application/Routers/RouteList.php
src/Application/Routers/SimpleRouter.php
src/Application/UI/Presenter.php
src/Bridges/ApplicationDI/RoutingExtension.php
src/Bridges/ApplicationTracy/RoutingPanel.php
tests/Application/Application.run.phpt
tests/Bridges.DI/RoutingExtension.cache.phpt
tests/Routers/Route.php
tests/Routers/RouteList.addRoute.phpt
tests/Routers/RouteList.withModule.phpt

Routers in nette/routing are pure, without any reference to concepts such as presenter / action. So they can't have:
1) constructors like `Route('mask', 'Presenter:action')`, only `Route('mask', ['presenter' => 'Presenter', 'action' => 'action'])`
2) support for special parameter `module`
So there are descendants in nette/application, which add this functionality.
The problem is that there are two classes in Nette like `Nette\Routing\Route` and `Nette\Application\Routers\Route` (in a similar relationship like `Nette\Forms\Form` and `Nette\Application\UI\Form`), which is not good. That's why I take this as a concept, not something ready to merge.

Separated routing to nette/routing

---

src/Application/Application.php

`$presenter === null` cannot happen as it fails on `!is_string($presenter)`

Fix error conditions order

---

src/Application/UI/Presenter.php

Added new onRender event, right after beforeRender and before actual render happends (as put it before beforeRender and called it onRender is confusing)
- Type: new feature
- BC break: noe
- doc PR: none
If we want to use traits in project, and mainly in extensios, there should be easy way, how to push somethink into template, but only if template is used. We have onStartup and onShutdown methods, but they are not ideal for this, as onStartup is called even if no reder<action> is performed, so if i add somethink to template there, it will cost me time of template creation, that will never use if redirect is called.
We have beforeRender and afterRender, but that is only methods, so we can modify them with trait.
I suggest new onRender method, that is called right after beforeRender, before …

Presenter: added onRender event

---

src/Application/UI/Presenter.php

- bug fix
- BC break? no
Simply safe replace `$this` to `self::` in case of static method.

Fix $this to self:: in case of static method.

---

src/Bridges/ApplicationTracy/templates/RoutingPanel.panel.phtml

- new feature
- BC break? no
My suggestion for better responsivity in case of resize window. This feature is very helpful when you must resize Tracy panel in small notebook screen or on mobile phone in case of debug by frontend developer in company local network.
New features:
1. Main table with `width: 100 %` for better user experience.
2. In case of medium size wrap lines around slashes in `Mask / Class` by `<wbr>` and keep slash before string on each new lines.
3. Wrap URL parameters or path or both:
Thanks.

RoutingPanel: Add better panel responsivity

---

src/Application/exceptions.php

- bug fix
- BC break? no
https://www.php.net/manual/en/class.exception.php
```
public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )
```
The third parameter can be only \Throwable

BadRequestException parent Exception expect Throwable

---

src/Application/UI/Presenter.php

- new feature?
- BC break? no
Mark optional parameters as required (without `= null`), because parameter `$httpRequest` is required.
Removed set default value as `null`, because in real code user must define value. Only marked as nullable.

Presenter: injectPrimary() params are required because $httpRequest is required

---

src/Application/UI/Presenter.php
tests/UI/Presenter.isModuleCurrent().phpt

- new feature
@dg has already added `$presenter->getModule()` method, which is universal. I've added an alternative to `$presenter->isLinkCurrent()` for modules.
- doc PR: nette/docs#???  I'd send PR if accepted. I've checked current doc and send small PR (https://github.com/nette/docs/pull/790). I would propose to describe new behavior in same section.

Presenter: added isModuleCurrent() [Closes #240]

---

src/Application/Responses/FileResponse.php

- bug fix? yes
- BC break? no
If the file has strict privileges, it will crash the entire application.

FileResponse: added some checks

---

src/Application/UI/Control.php
src/Application/UI/Presenter.php

- new feature
- BC break? no
- doc PR: nette/docs#???  
Based on the discussion in https://forum.nette.org/en/32893-custom-template-class-for-presenter-and-control-experimental-feature#p207624, I added parameters to these methods. Is it ok like this?

Control, Presenter::createTemplate() added parameter $class for custom creation of the Template

---

src/Bridges/ApplicationTracy/templates/RoutingPanel.panel.phtml

- bug fix
- BC break? no
Old behavior:
New more better behavior (because minus `-` is more often character):

RoutingPanel: Better mask responsivity.

---

src/Application/UI/Component.php
src/Bridges/ApplicationLatte/Template.php

Changed annotated method return type to match non-deprecated behavior to satisfy static analysis. It would complain anyway, if user added hidden parameter to return null.

Component->getPresenter() return type

---

src/Bridges/ApplicationLatte/Template.php
src/Bridges/ApplicationTracy/RoutingPanel.php
src/Bridges/ApplicationTracy/templates/RoutingPanel.panel.phtml

- new feature
- BC break? no
I think in case of some Custom router throws exception it can be rendered in Tracy panel.
Current behavior (with callstack):
New behavior (with marked route and `x` symbol):
I think this is more better. :)
Thanks.

RoutingPanel: Add support for render routes with exception.

---

src/Application/UI/Presenter.php

- bug fix 
- BC break? no
If someone constructs a URL that looks like `example.com/?1-foo=bar`, Nette crashes with this error:
> Argument 1 passed to Nette\ComponentModel\Container::getComponent() must be of the type string, int given, called in vendor/nette/application/src/Application/UI/Presenter.php on line 217

Prevent TypeError

---

src/Application/UI/Control.php

- bug fix for #271
- BC break? no (fixes BC break)
This allows behaviour which was supported before phpdoc was added. (there used to be `mixed` type for this parameter)
cc @dakur

flashMessage: allow HtmlStringable as a message

---

src/Bridges/ApplicationDI/LatteExtension.php

- bug fix
- BC break? no
Current version fails in case of `!isset($template->control) && $all === true`.
This PR fixes the problem and adds support for `$template->presenter` in case that `$template->control` is undefined

LatteExtension: fix undefined property

---

src/Bridges/ApplicationDI/LatteExtension.php

Latte TemplateFactory have `createTemplate()` extended for `$class` parameter and more accurate return typehint, which are both frequently used. This allows `TemplateFactory` to be autowired by `ApplicationLatte\TemplateFactory` type and prevent users confusion (like [here](https://forum.nette.org/en/34214-how-to-use-callbacks-in-services) and [here](https://forum.nette.org/cs/34209-factory-problem-s-construct))
Also some hint explaining why autowiring does not work when user sees in its DIC that service of requested type is available could be super helpful, but I have no idea how complicated the implementation would be

LatteExtension: changed UI\TemplateFactory type to ApplicationLatte\TemplateFactory

---

src/Bridges/ApplicationDI/LatteExtension.php

- bug fix #287
- BC break? no
I hit the #287 too. After Latte upgrade and with my own `UI\TemplateFactory` implementation in DI (with `ApplicationLatte\TemplateFactory` autowiring off) container buid fails.
I thik this fix will work but it's a pitty that one lost new great latte panel. So it is more or less hotfix. Maybe to find another way how to hook the panel to template, maybe via decorator, but I'm sure how to do it.

LatteExtension: inject interface to be more compatible

---

src/Application/UI/Component.php

- bug fix / new feature?   no / not really
- BC break? no
Adds `@return never` to `Component::redirect()` and `Component::redirectPermanent()`, useful for static analysis and required when any method using either of those wants to use `never` as its return type declaration (`function foo(): never`).
`Presenter::redirectUrl()` already [uses it](https://github.com/nette/application/blob/25e61b0de03bdb75a79ce5c72badcd4d3d6c4f01/src/Application/UI/Presenter.php#L609), this PR "propagates" it further.
Thank you!

Add `@return never` to redirect methods

---

src/Application/UI/Multiplier.php

- bug fix
- BC break? no
We used this functionality in Nette 2.4; now it is still allowed in Container::createComponent().

allow Multiplier::createComponent() to return a null

---

src/Bridges/ApplicationTracy/RoutingPanel.php

RoutingPanel displays name of current presenter with current action method and link to presenter class file in IDE. In case that method of current presenter doesnt exists - this link is missing. Proposed change of code fixes this small bug.
- bug fix YES
- BC break? NO
- doc detailed description on nette forum: https://forum.nette.org/cs/36505-poopravit-proklik-z-routingpanelu-do-souboru-presenteru-v-ide#p226916

Missing link from RoutingPanel.php to presenter class file in IDE
